language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then pecl install Phar; fi
  - composer install

script: ./vendor/bin/phpunit tests/
